version: '3.8'
networks:
  fleet-net:
    #name: fleet-net
    #driver: bridge
services:
  db:
    image: mysql
    restart: unless-stopped
    env_file: 
      - ./.env
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=PasswordPassword123
      - MYSQL_DATABASE=fleet
    networks:
      - fleet-net
  
  go-app:
    build: ./
    ports:
      - "8080:8080"
    depends_on: 
      - db
    env_file: 
      - ./.env
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=db
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
    restart: unless-stopped
    networks:
      - fleet-net
      

      