version: '3.8'
networks:
  fleet-net:
services:
  db:
    image: mysql
    restart: unless-stopped
    env_file: 
      - ./.env
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=PasswordPassword123
      - MYSQL_DATABASE=fleet
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - fleet-net

  
  go-app:
    build: ./
    ports:
      - "8080:8080"
    depends_on: 
      - db
    env_file: 
      - ./.env
    environment:
      - DB_USER=root
      - DB_PASSWORD=PasswordPassword123
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=fleetDB
    restart: unless-stopped
    networks:
      - fleet-net
  
  mqtt-server:
    build: ../mqtt-server
    ports:
      - "1883:1883"
    restart: unless-stopped
    networks:
      - fleet-net

  drone:
    build: ../drone-software
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - fleet-net
    

      

volumes:
  db-data: